import PlayerTokenWallet from "../views/players/player-token-wallet"

export const LogIn = {
    LogIn_Footer_Text: " 2022 Game Play Network, Inc. Patent Protected. All Rights Reserved",
    Application_Title: "Fusion Merchant Portal",
    LblUserName: "Username",
    LblPassword: "Password",
    LblContactSupport: "Contact Support",
    LblContactSupportModalBeforeLink: "Email",
    LblContactSupportModalAfterLink: " for account related issues, questions or any other concerns.",
    Contact_Support_Email: "support@gameplaynetwork.com",
    BtnSignIn: "Sign In",
    ErrMsgIncorrectUserNamePassword: "The username and password you entered is incorrect.",
    MsgSuccessfullyLoggedIn: "You are successfully logged in.",
    LblSignOut: "Sign Out"
}

export const MenuItems = {
    Menu_Dashboard_Title: "Dashboard",
    Menu_Dashboard_PageHeader: "Dashboard",
    Menu_Players_Title: "Players",
    Menu_Players_PageHeader: "Players Search",
    Menu_Orders_Title: "Orders",
    Menu_Orders_PageHeader: "Orders",
    Menu_PlayersDetails_Title: "Player Details",
    Menu_PlayersDetail_PageHeader: "Players",
}

export const Dashboard = {
    LblWelcome: "Welcome!",
    LblDashboardText1: "This website is for Partners using GPN’s Fusion platform.",
    LblDashboardText2: "It lets you find players, view their orders, token wallets, and other details."
}

export const Players = {
    BtnSearch: "Search",
    lblSearchPlaceHolder: "Player ID or Player Merchant Reference.",
    LblNoSearchResultsFound: "No search results found",
    GrdHeadPlayerId: "Player ID",
    GrdHeadMerchantReference: "Merchant Reference",
    GrdHeadAccountStatus: "Account Status",
    GrdHeadWageringStatus: "Wagering Status",
    GrdHeadUpdated: "Updated",
    LblPlayersResultsTable: "Players Information",
    LblPlayerSearchResultsTable: "Player Search Result",
    LblShow: "Show",
    LblEntries: "Records",
    LblPage: "Page",
    LblOf: "of",
    LblGoToPage: "Go to page",
    BdgActive: "Active",
    BdgSuspended: "Suspended",
    BdgClosing: "Closing",
    BdgClosed: "Closed",
    BdgCanceling: "Canceling",
    BdgCanceled: "Canceled",
    BdgApproved: "Approved",
    BdgUnapproved: "Unapproved",
    BdgReceived: "Received",
    BdgRejected: "Rejected",

    BdgVerifyingPlayer: "Verifying Player",
    BdgReserving: "Reserving",
    BdgReserved: "Reserved",
    BdgSendingtoWallet: "Sending to Wallet",
    BdgCompleted: "Completed",
    
    LblTotalSpent: "Total Spent",
    LblCreditBalance: "Credit Balance",
    LblPlayerIDStatusDetail: "Status Details",
    LblAccountStatus: "Account Status",
    LblWageringStatus: "Wagering Status",
    LblUpdated: "Updated",
    LblCreated: "Created",
    LblReason: "Reason",
    LblMerchantReference: "Merchant Reference",
    LblPlayerId: "Player ID",
    PlayerOrder: {
        LblPlayersOrderTable: "Order History",
        LblNoResultsFound: "No result found",
        GrdHeadOrderId: "Order ID",
        GrdHeadCreditAmount: "Credits (USD)",
        GrdHeadOrderStatus: "Order Status",
        GrdHeadLastUpdated: "Last Update",
        GrdHeadMerchantReference: "Merchant Reference",
    },
    PlayerTokenWallet: {
        HeadTokenWallets: "Token Wallets",
        LblCreditsBalance: "Credits Balance",
        LblPrizeBalance: "Prize Balance",
        LblDetailsNotFound: "Details not found",
        LblWalletName: "Wallet Name",
        HeadTokenWalletDetails: "Token Wallet Details",
        LblWalletTypeCode: "Wallet Type Code",
        LblWalletId: "Wallet ID",
        LblMerchantReference: "Merchant Reference",
        HeadOrderDetails: "Order Details",
        LblOrderId: "Order ID",
        LblRTP: "RTP%",
        LblOrderMerchantReference: "Order Merchant Reference",
        LblCreditAmount: "Credit Amount",
        LblTotalCostAmount: "Total Cost Amount",
        HeadOrderPlacedfrom: "Order Placed From",
        LblLatitude: "Latitude",
        LblLongitude: "Longitude",
        LblStateId: "State ID",
        LblPostalCode: "Postal Code",
        LblOrderStatus: "Order Status",
        HeadOrderLineItem: "Order Line Item(s)",
        LblItemCostAmount: "Item Cost Amount",
        LblItemType: "Item Type",
        LblOrderDeliveredTo: "Order Delivered To",
        HeadOrderResults: "Order Results",
        LblFinalCostAmount: "Final Cost Amount",
        LblOrderedCreditAmount: "Ordered Credit Amount",
        LblDeliveredCreditAmount: "Delivered Credit Amount",
        LblorderedCostAmount: "Ordered Cost Amount",
        LblRefundedAmount: "Refunded Amount",
        LblFinalCostAmount: "Final Cost Amount",
        LblPrizeAmount: "Prize Amount",
        HeadTaxableAmounts: "Taxable Amounts",
        LblTaxableWinnings: "Taxable Winnings",
        LblFederalWithholding: "Federal Withholding",
        LblStateWithholding: "State Withholding",
        LblLocalWithholding: "Local Withholding",
        LblNetWinnings: "Net Winnings",
        HeadTokenDetails: "Token Details",
        LblTokenWalletID: "Token Wallet ID",
        LblTokenID: "Token ID",
        LblTokenMerchantReference: "Token Merchant Reference",
        LblTokenReservedCreditAmount: "Token Reserved Credit Amount",
        LblTokenReservedPrizeAmount: "Token Reserved Prize Amount",
        LblTokenReservedDescription: "Token Reserved Description",
        LblTokenStatus: "Token Status",
        LblTokenRevealedPrizeAmount: "Token Revealed prize_amount",
        LblTokenRevealedDescription: "Token Revealed description",
        LblTokenRevealedCreditAmount: "Token Revealed credit_amount",
        LblTokenReservedAt: "Token Reserved At",
        LblTokenRevealedAt: "Token Revealed At",
        HeadOrdersDelivered: "Orders Delivered",
        MsgNoOrderDeliveredFound: "No Order Delivered Found",
        LblCreated: "Created",
        LblStatus: "Status",
        MsgNoGameplayTokenFound: "No Gameplay Token Found",
        HeadGameplayTokens: "Gameplay Tokens",
        LblTokenDescription: "Token Description"

    }
}

export const Footer = {
    footertext: "2022 Game Play Network, Inc. Patent Protected. All Rights Reserved. ",
    footerTermOfUse: "Terms of Use",
    footerPolicy: "Privacy Policy"
}